services:
  runner-1:
    build: .
    platform: linux/amd64
    container_name: event-me-gh-runner-1
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=event-me-runner-1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner-2:
    build: .
    platform: linux/amd64
    container_name: event-me-gh-runner-2
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=event-me-runner-2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
